### ISSUE TITLE
Missing ClaRa library

### ISSUE THREAD

**Issue by filip-jezek** [xogeny/impact#111]
The ClaRa library (https://www.claralib.com/), mostly opensource (with the exception of the tlk-media subset), mature library for thermodynamical modeling, is missing from the list. This leads to some doubts, whether the list is complete.

**Comment by dietmarw** [comment]
The impact list is currently generated based on what is forked by @modelica-3rdparty. Since Clara is not on GitHub or any other public repository that could be automatically synced to @modelica-3rdparty it will not enter the index.
