### ISSUE TITLE
Per repository credentials

### ISSUE THREAD

**Issue by xogeny** [xogeny/impact#32]
It occurs to me that creating private repository indices will require credentials on
a per repository basis.  We don't really have a mechanism to do that right now.

One possibility would be to incorporate it into the URL listed in the index somehow.

**Comment by xogeny** [comment]
In general, it is bad form to require users to store such things in files.  I propose we stick with the current scheme of pulling a GITHUB auth token from an environment variable.  I think this should handle most cases gracefully.  Closing for now and we can reopen it when we get to a point where we see this as a real limitation.

**Comment by dietmarw** [comment]
Agreed.
