### ISSUE TITLE
Use star info from GitHub API

### ISSUE THREAD

**Issue by mtiller** [xogeny/impact#37]
This gives some sense of community interest.

**Comment by xogeny** [comment]
Not sure what we will do with the information, but [it is included in crawl data](https://github.com/xogeny/impact/blob/master/index/library.go#L29) and [it is stored](https://github.com/xogeny/impact/blob/master/sample_index.json#L87).

**Comment by dietmarw** [comment]
I could think of including it on the modelica.org/libraries listing.

**Comment by dietmarw** [comment]
(which would make MSL look rather bad :-D)
