### ISSUE TITLE
Check version annotation

### ISSUE THREAD

**Issue by xogeny** [xogeny/impact#7]
We should technically check the version annotation to make sure it matches the tag we are using to infer version number.

**Comment by xogeny** [comment]
At this point, I have not implemented this.  I think it is sufficient to go with the tag version for now.  I consider this a "nice to have" feature, but I don't think it is a high priority.  I'd say let's consider reopening it if it really turns out to be an issue.

**Comment by dietmarw** [comment]
I agree. By depending less on the Modelica internals but stick to impact related information (e.g., `impact.json`) we avoid trouble.
