### ISSUE TITLE
Should impact refresh also accept <name>.mo libs?

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#76]
Whilst trying to build a json file which includes M_S_L I noticed that apparently *impact* currently does not support libraries of the shape:
 * `<name>.mo`
 * `<name> <version>.mo`

Question is should we support this or should we rather say that such a file name release is not a good structure anyway and "force" users to the proper `<name>[ <version>]/package.mo` structure if they want to be impact compatible?

**Comment by xogeny** [comment]
I think this can be handled by the new `impact.json` file.  Closing for now.  Reopen if still an issue.
