### ISSUE TITLE
`source_list` parameter overwrites defaults 

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#77]
When looking at [refresh.py#L177](https://github.com/xogeny/impact/blob/master/impactlib/refresh.py#L177) it looks like the intended behaviour of impact configuration is that one can define a `source_list` in **addition** to the existing default one. But in reality it seems that the presence of `source_list` parameter in the configuration file **overwrites** any existing defaults. 

Is that the way we want it?

**Comment by xogeny** [comment]
Closing.  This was about the Python version.  Reopen once the issue crops up with the Go version
