### ISSUE TITLE
Implement an algorithim for dependency calculations

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#84]
@mtiller has already been busy implementing a dependency algorithm in the [dependencies branch](../tree/dependencies). This still needs to be tested and then merged into master.

**Comment by xogeny** [comment]
I'm going to close this.  I think the dependency stuff is done.  It might have bugs or improvements.  But I don't think this issue should stay open.

**Comment by dietmarw** [comment]
How about removing the `dependencies` branch as well, since it is now merged anyway. Any reason to keep it?

**Comment by mtiller** [comment]
Yes, I think we can get rid of it.

**Comment by dietmarw** [comment]
Done.
