### ISSUE TITLE
Data should contain github/git URL for applications that wish to access non-release version

### ISSUE THREAD

**Issue by harmanpa** [xogeny/impact#91]
If an application wishes to access libraries that have either not been released, or access current development version, they would need a URL to the repository. This is not currently in the indexed data.

**Comment by xogeny** [comment]
Good point.  I think that we might want to think about this in the context of #31 as well.  When people build up a dependency list, it will be difficult to express in Modelica annotations dependencies like this.  So this is also a use case to consider in #31.

**Comment by xogeny** [comment]
This was added in 5b1149bed7f54f4cea22a38a30525e8c00f310d1
