### ISSUE TITLE
Determine "real" repository

### ISSUE THREAD

**Issue by xogeny** [xogeny/impact#93]
Currently, `modelica-3rdparty` ends up being owner for everything.  But I suspect if I dig deeper into the `Source` repository in the GitHub API, I can determine the "real" owners, repositories, etc.

**Comment by dietmarw** [comment]
Just some info for the status quo. When ever there is a 3rd party actively developing the library on GH than the modelica-3rdparty will always be a fork of that original library and we put the repo origin address in the `homepage` field (also linked from modelica.org/libraries). If for some reason the developer decides to develop not in GH than the modelica-3rdparty is *not* a fork but still contains the project address in the url field. 
So basically the three current variants are:

1. Project lives in its own GH repo:
  - modelica-3rdparty is a fork
  - `homepage` points to fork address **or** a proper project website 
2. Project lives outside GH
  - modelica-3rdparty is **not** a fork but a mirror
  - `homepage` points to project website or external repo address
3. Project does not have a dedicated GH repo elsewhere:
  - modelica-3rdparty is a **not** a fork but is primal development repo (even with the external developers being contributors (we try to discourage this and try to convince them to over take that project and let us fork instead to be able to reach status 1) 
  - `homepage` points to modelica-3rdparty GH repo address

**Comment by xogeny** [comment]
I looked into this a bit and was surprised by some of the limitations of the GitHub API.

Regarding point 1, it is nearly impossible to get access to the repository information of the **source** repository (the one being forked).  Yes, I can use the homepage to go to the *web page*.  But I wanted to extract information about the maintainer (email address, etc) and short of screen scraping, I don't see how to do that.  Furthermore, I'm trying to handle forks of repositories (libraries with the same name but have diverged in version control) and this makes it very hard to do that.  :-(

Regarding point 2, there is something called a mirrorURL that I could use.  But I can traverse that to get information about the author.  So almost the same limitations.

For point 3, things are simpler (since modelica-3rd party seems to own it).  But then we have the problem that it masks information about the original developer.

I really had not imagined it would be so hard to get such information.  The API provides lots of information.  But traversing to the parent repository looks to be quite difficult. :-(

**Comment by dietmarw** [comment]
So basically what this means is we need to include this kind of information manually in the `impact.json`? 

We should probably include those fields anyway even though some might be supported by the GH API already (It might be worth to also file a ticket against GH API to include the ones that we missing. So that *if* it is included one day we can switch). Having the backup in the manual `impact.json` allows also support other APIs at one point.

**Comment by harmanpa** [comment]
Is this question on SO not describing this issue?: http://stackoverflow.com/questions/18580913/github-api-for-a-forked-repository-object-how-to-get-what-repository-its-fork

**Comment by xogeny** [comment]
I couldn't find any documentation about `source` and `parent` either on [the GitHub page related to listing repositories](https://developer.github.com/v3/repos/#list-user-repositories) or in [the documentation for the Go client I'm using](http://godoc.org/github.com/google/go-github/github#Repository) (because I mistakenly searched for `Source`).  I assumed they played roles like that.  The problem is that they aren't set (using the client library I'm using).  But I'm glad you pointed this out because now I suspect it is more related to how I got my repository instance.  So perhaps I can find a way to get that information if I refetch the repository in some way.  I'll look into it, thanks.

**Comment by xogeny** [comment]
OK, I figured it out using Pete's hint.  The issue is that when you list repositories (e.g., all repositories owned by `modelica-3rdparty`), you get a `*github.Repository` object that has quite a bit of information in it.  But it isn't actually complete.  If you want the complete information (specifically, the `source` and `parent`!!!), you need to `get` that repository.  Seems a bit silly since I thought I already **had** that repository.

The fact that this information isn't provided by the `list` action isn't documented in either the [GitHub v3 api](https://developer.github.com/v3/repos/#list-user-repositories) documentation or [the Go client documentation](http://godoc.org/github.com/google/go-github/github#RepositoriesService.List).  Oh well, fortunately we've got @harmanpa to dig deep on this.

But now we have a deeper question.  What do we do with this information?  I've opened issue #94 to explore how to handle forks.
